spring:
  profiles:
    active: peer2
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 5000
  instance:
    hostname: peer2
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://peer1:7101/eureka/,http://peer3:7103/eureka/
server:
  port: 7002