---
spring:
  profiles:
    active: peer1
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://root:root@peer2:7002/eureka/,http://root:root@peer3:7003/eureka/
server:
  port: 0

---
spring:
  profiles:
    active: peer2
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://root:root@peer1:7001/eureka/,http://root:root@peer3:7003/eureka/

---
spring:
  profiles:
    active: peer3
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://root:root@peer1:7001/eureka/,http://root:root@peer2:7002/eureka/